### ISSUE TITLE
Presto client doesnt bind to Prestissimo service under Android 5.0.1+

### ISSUE THREAD

**Issue by mikeyscott** [TheRealFalcon/Prestissimo#28]
Was using very successfully your client and service for a complete drop-in variable-speed replacement for the Android media player for our Voice Dream Reader product. However after upgrading our build environment /target SDK level to 21  found the service was no longer being launched so client was just falling back to the regular Android media player without variable speed. 

Looks like there was an issue introduced with implicit vs explict intents in SDK 21 - I notice someone in AntennaPod project fixed this for that but it would be great to include this fix in this project if possible?

Thanks

**Comment by TheRealFalcon** [comment]
Take a look at #25 . It's a weird scenario because Prestissimo is decoupled from Presto so (conceptually) it shouldn't be too hard for apps to incorporate the functionality. Unfortunately, the original Presto service (the part you probably used in your app) is where the fix needs to happen, and I don't maintain or control that. In #25, the commit where AntennaPod fixed it is there. Please reference that.

**Comment by mikeyscott** [comment]
Ah - sorry didnt quite appreciate that you were not in control of the Presto client where the fix needed to happen. I've incorporated the fix from AntennaPod and all works well again now.
